# Generated by Django 4.2.2 on 2023-06-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errands', models.CharField(max_length=50)),
                ('home', models.CharField(max_length=50)),
                ('finances', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('travel', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=50)),
            ],
        ),
    ]
