# Generated by Django 4.2.2 on 2023-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='errands',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='finances',
        ),
        migrations.RemoveField(
            model_name='category',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='category',
            name='home',
        ),
        migrations.RemoveField(
            model_name='category',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='category',
            name='work',
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='main_app.category'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
