# Generated by Django 4.2.1 on 2023-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_favoritequote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritequote',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='favoritequote',
            name='quote',
            field=models.CharField(max_length=500),
        ),
    ]
