# Generated by Django 4.2.1 on 2023-06-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_quote_alter_task_when'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author',
            new_name='a',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_text',
        ),
        migrations.AddField(
            model_name='quote',
            name='q',
            field=models.CharField(default='<your_default_value>', max_length=500),
        ),
    ]
