# Generated by Django 4.2.1 on 2023-06-10 05:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_rename_author_quote_a_remove_quote_quote_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritequote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='a',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='q',
        ),
        migrations.AddField(
            model_name='favoritequote',
            name='quote_text',
            field=models.CharField(default='Your default value here', max_length=500),
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default=datetime.datetime(2023, 6, 10, 5, 48, 6, 76467, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_text',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritequote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_quotes', to='main_app.quote'),
        ),
    ]
