# Generated by Django 4.2.1 on 2023-06-10 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_remove_favoritequote_user_remove_quote_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritequote',
            name='quote_text',
        ),
        migrations.AddField(
            model_name='favoritequote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritequote',
            name='quote',
            field=models.CharField(max_length=500),
        ),
    ]
