# Generated by Django 4.2.2 on 2023-06-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_task_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='quotes',
        ),
    ]
